name: bp_frozen
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - bwa=0.7.17
  - samtools[version='>=1.10']
  - bcftools
  - bedtools
  - vcftools
  - sambamba
  - vt=0.57721
#  - picard=2.17.4
  - picard=2.27.3
  - gatk=3.7
#  - gatk4=4.1.2
  - gatk4=4.2.6
#  - root_base=6.20.6
#  - bioconda::cnvnator=0.4.1
  - bioconda::cnvnator
#  - ucsc-fetchchromsizes
#  - ucsc-bigwigaverageoverbed
#  - ucsc-wigtobigwig
#  - ucsc-liftover
  - scipy
  - numpy
  - pandas
  - awscli
  - synapseclient
  - statsmodels
  - rpy2
  - pysam
  - pysamstats
  - pyfaidx
  - regex
  - parallel
  - r-rcolorbrewer
  - r-ggplot2
  - r-paramhelpers
  - r-devtools
  - r-randomforest
  - r-e1071
  - r-nnet
  - r-mlr
  - r-xml
  - r-glmnet
  - r-caret
  - hcc::lftp[version='>=4.9.1']
  - google-cloud-sdk
  - pip
  - pip:
    - crcmod
