export LD_LIBRARY_PATH=$LD_LIBRARY_PATH_BACKUP
unset LD_LIBRARY_PATH_BACKUP
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH_BACKUP
unset PKG_CONFIG_PATH_BACKUP
export CFLAGS="$CONDA_BACKUP_CFLAGS"
export LDFLAGS="$CONDA_BACKUP_LDFLAGS"
